Fix bug loading AWS credentials that stopped alert-deletion & SNS
AWS placed our SES account under review on Saturday 15th February:

https://groups.google.com/a/guardian.co.uk/d/msg/aws-ophan/F880jhVL2yY/Wz_iVkkZAQAJ

> Your current bounce rate is 10.63%. We measured this rate over the last
> 10,028 eligible emails* you sent. Our analysis covers the last 4.3 days.

This was due to AWS-credential-loading in the Ophan Housekeeper lambda
being broken by commit 31cec53c65 back in October 2019:

https://github.com/guardian/ophan-housekeeper/pull/5/files#r379906348

I should have used `EnvironmentVariableCredentialsProvider`, not
`EC2ContainerCredentialsProviderWrapper` (see eg.
https://stackoverflow.com/a/32410565/438886 or
https://github.com/guardian/mobile-n10n/pull/156) - with credential-loading
broken, the lambda couldn't load the AWS credentials it needed to delete
entries from the `ophan-alerts` DynamoDB table, or post to the SNS topic.

Perhaps surprisingly, the Ophan Housekeeper lambda _only_ needs those AWS
credentials when it's dealing with a permanently bouncing email - so there
was no obvious problem until a permanent bounce occurred, starting at
13:26 on February 12th 2020, when these errors started:

https://logs.gutools.co.uk/s/ophan/app/kibana#/doc/581f7b00-c4df-11e9-bc08-9d1af4d9c1d5/logstash-ophan-2020.02.12?id=ciyUOXABBviLcZqRrCAI&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-02-12T13:26:31.042Z',to:'2020-02-12T13:26:40.791Z'))
```
Unable to load AWS credentials from any provider in the chain: [com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@1e730495: Unable to load credentials from service endpoint, com.amazonaws.auth.profile.ProfileCredentialsProvider@7d3a22a9: profile file cannot be null]: com.amazonaws.SdkClientException
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@1e730495: Unable to load credentials from service endpoint, com.amazonaws.auth.profile.ProfileCredentialsProvider@7d3a22a9: profile file cannot be null]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
...
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4805)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4772)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:2641)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:2607)
	at org.scanamo.ops.ScanamoSyncInterpreter.apply(ScanamoSyncInterpreter.scala:35)
```

As the lambda was broken, it wasn't able to decommission the relevant
Ophan Alerts - so Trigr kept on sending them, and there were so many of
them, bouncing permanently, that AWS placed our SES account under review.

Once this fix has been merged, it should hopefully resolve the issue.

https://logs.gutools.co.uk/s/ophan/goto/74968773d968bb5f2b8f285bd3354002